version: '3.7'
volumes:
  mlflow:
    name: mlflow 
  minio:
    name: minio
services:
 
  mlflow:
    labels:
      com.example.service: "mlflow"
      com.example.description: "Experiments visualisation"
    image: mlflow:latest
    volumes:
      - mlflow:/mlruns:rw
    environment:
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY:-depth}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY:-depth123}
      - MLFLOW_S3_ENDPOINT_URL=http://localhost:9000
    container_name: mlflow
    network_mode: "host"
  minio:
    labels:
      com.example.service: "minio"
      com.example.description: "Minio storage"
    image: minio/minio:latest
    container_name: minio
    volumes:
      - minio:/data/minio:rw
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY:-depth}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY:-depth123}
    ports:
      - "9000:9000"
    deploy:
      restart_policy:
        delay: 10s
        window: 60s
      placement:
        constraints:
          - node.labels.minio==true
    command: server /data/minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
